### ISSUE TITLE
关于微信sdk语音问题

### ISSUE THREAD

**Issue by itcats** [netputer/wechat-php-sdk#25]
请问下您在SAE上提供的微信程序怎么处理语音信息，我已经开启了接收语音识别结果，在Wechat.php中加入了![1](https://cloud.githubusercontent.com/assets/12854561/8122944/31bec72a-10f4-11e5-84d7-c5bc1fdcb16c.jpg)，也定义了![2](https://cloud.githubusercontent.com/assets/12854561/8122943/2dc7c018-10f4-11e5-8aae-6b959cb23682.jpg)，但是就是不能识别，情况是这样的![3](https://cloud.githubusercontent.com/assets/12854561/8122941/220b817e-10f4-11e5-8413-33a8612a8fe7.jpg)我收不到Recognition的值，怎么才能获取到。

**Comment by netputer** [comment]
`$this->getRequest('Recognition')`

**Comment by itcats** [comment]
返还结果还是为空，不报错，无输出，已加上分号
